version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          SERVICE_NAME: lumiere-javatest
          REGISTRY_URL: 336627915605.dkr.ecr.eu-central-1.amazonaws.com
          KUBERNETES_CONFIG_STORE: cluster-lumiere-dev-config
    branches:
       only:
           - /sprint[1-6]/
    steps:
      - run: |
          sudo apt-get install awscli
          mkdir ~/deployment
          export PATH=$PATH:~/deployment
          curl -L -o ~/deployment/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ~/deployment/kubectl          
      - checkout
      - setup_remote_docker
      - run: echo "Hola mundo"
      - restore_cache:
          key: ${SERVICE_NAME}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: ${SERVICE_NAME}-{{ checksum "pom.xml" }}      
      - run: mvn package      
      - run: |
          docker build -t ${SERVICE_NAME} -f Dockerfile .
          aws configure set default.region eu-central-1
          aws configure set default.output json
          eval $(aws ecr get-login --region eu-central-1)
          docker tag $SERVICE_NAME $REGISTRY_URL/$SERVICE_NAME:build-$CIRCLE_SHA1
          docker tag $SERVICE_NAME $REGISTRY_URL/$SERVICE_NAME:latest
          docker push $REGISTRY_URL/$SERVICE_NAME:build-$CIRCLE_SHA1
          docker push $REGISTRY_URL/$SERVICE_NAME:latest
          aws s3 cp s3://$KUBERNETES_CONFIG_STORE/kubeconfig ~/.kube/config
          ~/deployment/kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${REGISTRY_URL}/${SERVICE_NAME}:build-${CIRCLE_SHA1}
